export const FRUITS_OPTIONS = [
  'Akee',
  'Apple',
  'Apricot',
  'Avocado',
  'Açaí',
  'Banana',
  'Bell pepper',
  'Bilberry',
  'Black sapote',
  'Blackberry',
  'Blackcurrant',
  'Blood orange',
  'Blueberry',
  'Boysenberry',
  'Buddha`s hand',
  'Cantaloupe',
  'Cherimoya',
  'Cherry',
  'Chico fruit',
  'Chili pepper',
  'Clementine',
  'Cloudberry',
  'Coconut',
  'Corn kernel',
  'Crab apples',
  'Cranberry',
  'Cucumber',
  'Currant',
  'Damson',
  'Date',
  'Dragonfruit',
  'Durian',
  'Eggplant',
  'Elderberry',
  'Feijoa',
  'Fig',
  'Goji berry',
  'Gooseberry',
  'Grape',
  'Grapefruit',
  'Guava',
  'Honeyberry',
  'Honeydew',
  'Huckleberry',
  'Jabuticaba',
  'Jackfruit',
  'Jambul',
  'Japanese plum',
  'Jostaberry',
  'Jujube',
  'Juniper berry',
  'Kiwano',
  'Kiwifruit',
  'Kumquat',
  'Lemon',
  'Lime',
  'Longan',
  'Loquat',
  'Lychee',
  'Mandarine',
  'Mango',
  'Mangosteen',
  'Marionberry',
  'Melon',
  'Miracle fruit',
  'Mulberry',
  'Nance',
  'Nectarine',
  'Olive',
  'Orange',
  'Papaya',
  'Passionfruit',
  'Pea',
  'Peach',
  'Pear',
  'Persimmon',
  'Pineapple',
  'Pineberry',
  'Pitaya',
  'Plantain',
  'Plum',
  'Plumcot',
  'Pomegranate',
  'Pomelo',
  'Prune',
  'Pumpkin',
  'Purple mangosteen',
  'Quince',
  'Raisin',
  'Rambutan',
  'Raspberry',
  'Redcurrant',
  'Salak',
  'Salal',
  'Salmonberry',
  'Satsuma',
  'Soursop',
  'Squash',
  'Star apple',
  'Star fruit',
  'Strawberry',
  'Surinam cherry',
  'Tamarillo',
  'Tamarind',
  'Tangerine',
  'Tomato',
  'Ugli fruit',
  'Watermelon',
  'White currant',
  'White sapote',
  'Yuzu',
  'Zucchini',
]

export const DOCTORS_OPTIONS = [
  'Aerospace Medicine',
  'Anaesthesia',
  'Bariatric Surgery',
  'Cardiology - Interventional',
  'Cardiology - Non Interventional',
  'Cardiothoracic And Vascular Surgery',
  'Centre For Spinal Diseases',
  'Clinical Haematology And BMT',
  'Corneal Transplant',
  'Critical Care Medicine',
  'Dermatology And Cosmetology',
  'Ear Nose Throat Head And Neck Surgery',
  'Emergency Medicine',
  'Endocrinology',
  'General Surgery',
  'Infectious Diseases',
  'Internal Medicine',
  'In-Vitro Fertilisation (IVF)',
  'Laboratory Medicine',
  'Liver Transplant & Hepatic Surgery',
  'Maxillofacial Surgery',
  'Medical Gastroenterology',
  'Medical Oncology & Clinical Hematology',
  'Medical Oncology',
  'Minimally Invasive Gynecology',
  'Neonatology',
  'Nephrology',
  'Neuro Modulation',
  'Nutrition & Dietetics',
  'Neurology',
  'Neurosurgery',
  'Obstetrics And Gynecology',
  'Ophthalmology',
  'Orthopedics & Joint Replacement',
  'Pain Management',
  'Pediatric Surgery',
  'Physiotherapy',
  'Plastic Surgery',
  'Psychiatry',
  'Pulmonology',
  'Renal Transplant',
  'Reproductive Medicine & IVF',
  'Rheumatology',
  'Robotic Surgery',
  'Surgical Gastroenterology',
  'Surgical Oncology',
  'Urology',
  'Vascular and Endovascular Surgery',
]