export const FRUITS_OPTIONS = [
  'Açaí',
  'Apple',
  'Akee',
  'Apricot',
  'Avocado',
  'Banana',
  'Bilberry',
  'Blackberry',
  'Blackcurrant',
  'Black sapote',
  'Blueberry',
  'Boysenberry',
  'Buddha`s hand',
  'Crab apples',
  'Currant',
  'Cherry',
  'Cherimoya',
  'Chico fruit',
  'Cloudberry',
  'Coconut',
  'Cranberry',
  'Cucumber',
  'Damson',
  'Date',
  'Dragonfruit',
  'Pitaya',
  'Durian',
  'Elderberry',
  'Feijoa',
  'Fig',
  'Goji berry',
  'Gooseberry',
  'Grape',
  'Raisin',
  'Grapefruit',
  'Guava',
  'Honeyberry',
  'Huckleberry',
  'Jabuticaba',
  'Jackfruit',
  'Jambul',
  'Japanese plum',
  'Jostaberry',
  'Jujube',
  'Juniper berry',
  'Kiwano',
  'Kiwifruit',
  'Kumquat',
  'Lemon',
  'Lime',
  'Loquat',
  'Longan',
  'Lychee',
  'Mango',
  'Mangosteen',
  'Marionberry',
  'Melon',
  'Cantaloupe',
  'Honeydew',
  'Watermelon',
  'Miracle fruit',
  'Mulberry',
  'Nectarine',
  'Nance',
  'Olive',
  'Orange',
  'Blood orange',
  'Clementine',
  'Mandarine',
  'Tangerine',
  'Papaya',
  'Passionfruit',
  'Peach',
  'Pear',
  'Persimmon',
  'Plantain',
  'Plum',
  'Prune',
  'Pineapple',
  'Pineberry',
  'Plumcot',
  'Pomegranate',
  'Pomelo',
  'Purple mangosteen',
  'Quince',
  'Raspberry',
  'Salmonberry',
  'Rambutan',
  'Redcurrant',
  'Salal',
  'Salak',
  'Satsuma',
  'Soursop',
  'Star apple',
  'Star fruit',
  'Strawberry',
  'Surinam cherry',
  'Tamarillo',
  'Tamarind',
  'Ugli fruit',
  'White currant',
  'White sapote',
  'Yuzu',
  'Avocado',
  'Bell pepper',
  'Chili pepper',
  'Corn kernel',
  'Cucumber',
  'Eggplant',
  'Olive',
  'Pea',
  'Pumpkin',
  'Squash',
  'Tomato',
  'Zucchini',
]

export const DOCTORS_OPTIONS = [
  'Aerospace Medicine',
  'Anaesthesia',
  'Bariatric Surgery',
  'Cardiology - Interventional',
  'Cardiology - Non Interventional',
  'Cardiothoracic And Vascular Surgery',
  'Centre For Spinal Diseases',
  'Clinical Haematology And BMT',
  'Corneal Transplant',
  'Critical Care Medicine',
  'Dermatology And Cosmetology',
  'Ear Nose Throat Head And Neck Surgery',
  'Emergency Medicine',
  'Endocrinology',
  'General Surgery',
  'Infectious Diseases',
  'Internal Medicine',
  'In-Vitro Fertilisation (IVF)',
  'Laboratory Medicine',
  'Liver Transplant & Hepatic Surgery',
  'Maxillofacial Surgery',
  'Medical Gastroenterology',
  'Medical Oncology & Clinical Hematology',
  'Medical Oncology',
  'Minimally Invasive Gynecology',
  'Neonatology',
  'Nephrology',
  'Neuro Modulation',
  'Nutrition & Dietetics',
  'Neurology',
  'Neurosurgery',
  'Obstetrics And Gynecology',
  'Ophthalmology',
  'Orthopedics & Joint Replacement',
  'Pain Management',
  'Pediatric Surgery',
  'Physiotherapy',
  'Plastic Surgery',
  'Psychiatry',
  'Pulmonology',
  'Renal Transplant',
  'Reproductive Medicine & IVF',
  'Rheumatology',
  'Robotic Surgery',
  'Surgical Gastroenterology',
  'Surgical Oncology',
  'Urology',
  'Vascular and Endovascular Surgery',
]
