export const FRUITS_OPTIONS = [
  'Akee',
  'Apple',
  'Apricot',
  'Avocado',
  'Açaí',
  'Banana',
  'Bell pepper',
  'Bilberry',
  'Black sapote',
  'Blackberry',
  'Blackcurrant',
  'Blood orange',
  'Blueberry',
  'Boysenberry',
  'Buddha`s hand',
  'Cantaloupe',
  'Cherimoya',
  'Cherry',
  'Chico fruit',
  'Chili pepper',
  'Clementine',
  'Cloudberry',
  'Coconut',
  'Corn kernel',
  'Crab apples',
  'Cranberry',
  'Cucumber',
  'Currant',
  'Damson',
  'Date',
  'Dragonfruit',
  'Durian',
  'Eggplant',
  'Elderberry',
  'Feijoa',
  'Fig',
  'Goji berry',
  'Gooseberry',
  'Grape',
  'Grapefruit',
  'Guava',
  'Honeyberry',
  'Honeydew',
  'Huckleberry',
  'Jabuticaba',
  'Jackfruit',
  'Jambul',
  'Japanese plum',
  'Jostaberry',
  'Jujube',
  'Juniper berry',
  'Kiwano',
  'Kiwifruit',
  'Kumquat',
  'Lemon',
  'Lime',
  'Longan',
  'Loquat',
  'Lychee',
  'Mandarine',
  'Mango',
  'Mangosteen',
  'Marionberry',
  'Melon',
  'Miracle fruit',
  'Mulberry',
  'Nance',
  'Nectarine',
  'Olive',
  'Orange',
  'Papaya',
  'Passionfruit',
  'Pea',
  'Peach',
  'Pear',
  'Persimmon',
  'Pineapple',
  'Pineberry',
  'Pitaya',
  'Plantain',
  'Plum',
  'Plumcot',
  'Pomegranate',
  'Pomelo',
  'Prune',
  'Pumpkin',
  'Purple mangosteen',
  'Quince',
  'Raisin',
  'Rambutan',
  'Raspberry',
  'Redcurrant',
  'Salak',
  'Salal',
  'Salmonberry',
  'Satsuma',
  'Soursop',
  'Squash',
  'Star apple',
  'Star fruit',
  'Strawberry',
  'Surinam cherry',
  'Tamarillo',
  'Tamarind',
  'Tangerine',
  'Tomato',
  'Ugli fruit',
  'Watermelon',
  'White currant',
  'White sapote',
  'Yuzu',
  'Zucchini',
]
